<script>
  export let story;
  export let summary = null;
  export let summaryModel = null;
  export let error = null;
  export let isLoadingSummary = false;
  
  // Styling props for different story types
  export let textSize = 'base'; // 'sm', 'base', 'lg'
  export let padding = '4'; // '2', '3', '4'
  export let borderWidth = '4'; // '2', '4'
  export let variant = 'hero'; // 'hero', 'secondary', 'list'
  export let containerClass = '';
  
  $: textClass = textSize === 'sm' ? 'text-sm' : textSize === 'lg' ? 'text-lg' : 'text-base';
  $: paddingClass = `p-${padding}`;
  $: borderClass = `border-l-${borderWidth}`;
  
  // Background color based on variant
  $: backgroundClass = variant === 'secondary' 
    ? 'bg-[var(--color-background-card)]'
    : 'bg-[var(--color-background-dark-sections)]';
</script>

{#if summary}
  <div class="{textClass} {paddingClass} {backgroundClass} rounded-md {borderClass} border-[var(--color-secondary-accent)] {containerClass}">
    <p class="font-semibold {textSize === 'sm' ? 'text-md' : 'text-lg'} mb-1">TL;DR</p>
    <p class="text-[var(--color-secondary-text)] whitespace-pre-line">{summary}</p>
    {#if summaryModel}
      <p class="text-xs text-[var(--color-tertiary-text)] mt-2 italic">(Generated by {summaryModel})</p>
    {/if}
  </div>
{:else if isLoadingSummary}
  <div class="{textClass} text-justify {paddingClass} {backgroundClass} rounded-md animate-pulse {containerClass}">
    Loading summary...
  </div>
{:else if error}
  <div class="{textClass} text-justify {paddingClass} bg-red-100 text-red-700 rounded-md {containerClass}">
    {error}
  </div>
{/if}